openapi: 3.0.3
info:
  contact:
    email: tagtuna@gmail.com
    name: Tagbase Dev Team
    url: https://github.com/tagbase/tagbase-server/issues
  description: |
    tagbse-server provides HTTP endpoints for ingestion of various files \
    into a Tagbase SQL database. Input file support currently includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4) \
    and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)).
  license:
    name: Apache License v2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: TODO
  title: tagbase-server API
  version: v0.7.0
servers:
- description: Local development tagbase-server
  url: https://localhost/tagbase/api/v0.7.0
- description: ICCAT Test tagbase-server
  url: https://162.13.162.49/tagbase/api/v0.7.0
tags:
- description: Event Operations
  name: events
- description: Ingestion operations
  name: ingest
- description: Tag Operations
  name: tags
paths:
  /events:
    get:
      description: Get information about all events
      operationId: list_all_events
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events200'
          description: A list containing all events.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about all events
      tags:
      - events
      x-openapi-router-controller: tagbase_server.controllers.events_controller
  /events/{event_id}:
    get:
      description: Get information about an individual event
      operationId: get_event
      parameters:
      - description: Event UUID
        explode: true
        in: path
        name: event_id
        required: true
        schema:
          $ref: '#/components/schemas/event_id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event200'
          description: Information about an individual tag
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about an individual event
      tags:
      - events
      x-openapi-router-controller: tagbase_server.controllers.events_controller
    put:
      description: Update notes for an event
      operationId: put_event
      parameters:
      - description: Event UUID
        explode: true
        in: path
        name: event_id
        required: true
        schema:
          $ref: '#/components/schemas/event_id'
        style: simple
      - description: "Free-form text field where details of submitted eTUFF file for\
          \ ingest can be provided e.g. submitter name, etuff data contents (tag metadata\
          \ and measurements + primary position data, or just secondary solution-positional\
          \ meta/data)"
        explode: true
        in: query
        name: notes
        required: false
        schema:
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventPut200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Update the 'notes' associated with an event
      tags:
      - events
      x-openapi-router-controller: tagbase_server.controllers.events_controller
  /ingest:
    get:
      description: Get network accessible file and execute ingestion
      operationId: ingest_get
      parameters:
      - description: "Location of a network accessible (file, ftp, http, https) file\
          \ e.g. 'file:///usr/src/app/data/eTUFF-sailfish-117259.txt'."
        explode: true
        in: query
        name: file
        required: true
        schema:
          maxLength: 100
          minLength: 10
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - description: "Free-form text field where details of submitted eTUFF file for\
          \ ingest can be provided e.g. submitter name, etuff data contents (tag metadata\
          \ and measurements + primary position data, or just secondary solution-positional\
          \ meta/data)"
        explode: true
        in: query
        name: notes
        required: false
        schema:
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - description: "Type of file to be ingested, defaults to 'etuff'"
        explode: true
        in: query
        name: type
        required: false
        schema:
          default: etuff
          enum:
          - etuff
          - netcdf
          type: string
        style: form
      - description: Version identifier for the eTUFF tag data file ingested
        explode: true
        in: query
        name: version
        required: false
        schema:
          maxLength: 10
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingest200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get network accessible file and execute ingestion
      tags:
      - ingest
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
    post:
      description: Post a local file and perform a ingest operation
      operationId: ingest_post
      parameters:
      - description: Free-form text field to explicitly define the name of the file
          to be persisted
        explode: true
        in: query
        name: filename
        required: true
        schema:
          maxLength: 100
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - description: "Free-form text field where details of submitted eTUFF file for\
          \ ingest can be provided e.g. submitter name, etuff data contents (tag metadata\
          \ and measurements + primary position data, or just secondary solution-positional\
          \ meta/data)"
        explode: true
        in: query
        name: notes
        required: false
        schema:
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - description: "Type of file to be ingested, defaults to 'etuff'"
        explode: true
        in: query
        name: type
        required: false
        schema:
          default: etuff
          enum:
          - etuff
          - netcdf
          type: string
        style: form
      - description: Version identifier for the eTUFF tag data file ingested
        explode: true
        in: query
        name: version
        required: false
        schema:
          maxLength: 10
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: Compressed binary file containing one or more eTUFF files
              format: binary
              maxLength: 1000000000
              minLength: 1
              type: string
          text/plain:
            schema:
              description: Plain text eTUFF file
              format: text
              maxLength: 1000000000
              minLength: 1
              type: string
        required: true
        x-body-name: body
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingest200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Post a local file and perform a ingest operation
      tags:
      - ingest
      x-codegen-request-body-name: body
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
  /tags:
    get:
      description: Get information about all tags
      operationId: list_tags
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tags200'
          description: A list of all tags.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about all tags
      tags:
      - tags
      x-openapi-router-controller: tagbase_server.controllers.tags_controller
  /tags/{tag_id}:
    get:
      description: Get information about an individual tag
      operationId: get_tag
      parameters:
      - description: Numeric tag ID
        explode: true
        in: path
        name: tag_id
        required: true
        schema:
          type: number
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tag200'
          description: Information about an individual tag.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about an individual tag
      tags:
      - tags
      x-openapi-router-controller: tagbase_server.controllers.tags_controller
  /tags/{tag_id}/subs/{sub_id}:
    put:
      description: Update a tag submission
      operationId: put_tag
      parameters:
      - description: "Free-form text field where details of submitted eTUFF file for\
          \ ingest can be provided e.g. submitter name, etuff data contents (tag metadata\
          \ and measurements + primary position data, or just secondary solution-positional\
          \ meta/data)"
        explode: true
        in: query
        name: notes
        required: false
        schema:
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - description: Numeric tag ID
        explode: true
        in: path
        name: tag_id
        required: true
        schema:
          type: number
        style: simple
      - description: Numeric submission ID
        explode: true
        in: path
        name: sub_id
        required: true
        schema:
          type: number
        style: simple
      - description: Version identifier for the eTUFF tag data file ingested
        explode: true
        in: query
        name: version
        required: false
        schema:
          maxLength: 10
          minLength: 1
          pattern: ^(?!\s*$).+
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tagPut200'
          description: Message confirming successful data update
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml
      summary: Update the 'notes' and/or 'version' associated with a tag submission
      tags:
      - tags
      x-openapi-router-controller: tagbase_server.controllers.tags_controller
  /tags/{tag_id}/subs/{sub_id}/events:
    get:
      description: Get all events for a given tag submission
      operationId: list_events
      parameters:
      - description: Numeric tag ID
        explode: true
        in: path
        name: tag_id
        required: true
        schema:
          type: number
        style: simple
      - description: Numeric submission ID
        explode: true
        in: path
        name: sub_id
        required: true
        schema:
          type: number
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events200'
          description: Message confirming successful data update
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml
      summary: Get all events for a given tag submission
      tags:
      - events
      x-openapi-router-controller: tagbase_server.controllers.events_controller
components:
  parameters:
    event_id:
      description: Event UUID
      explode: true
      in: path
      name: event_id
      required: true
      schema:
        $ref: '#/components/schemas/event_id'
      style: simple
    filename:
      description: Free-form text field to explicitly define the name of the file
        to be persisted
      explode: true
      in: query
      name: filename
      required: true
      schema:
        maxLength: 100
        minLength: 1
        pattern: ^(?!\s*$).+
        type: string
      style: form
    notes:
      description: "Free-form text field where details of submitted eTUFF file for\
        \ ingest can be provided e.g. submitter name, etuff data contents (tag metadata\
        \ and measurements + primary position data, or just secondary solution-positional\
        \ meta/data)"
      explode: true
      in: query
      name: notes
      required: false
      schema:
        maxLength: 10000
        minLength: 1
        pattern: ^(?!\s*$).+
        type: string
      style: form
    subId:
      description: Numeric submission ID
      explode: true
      in: path
      name: sub_id
      required: true
      schema:
        type: number
      style: simple
    tagId:
      description: Numeric tag ID
      explode: true
      in: path
      name: tag_id
      required: true
      schema:
        type: number
      style: simple
    type:
      description: "Type of file to be ingested, defaults to 'etuff'"
      explode: true
      in: query
      name: type
      required: false
      schema:
        default: etuff
        enum:
        - etuff
        - netcdf
        type: string
      style: form
    version:
      description: Version identifier for the eTUFF tag data file ingested
      explode: true
      in: query
      name: version
      required: false
      schema:
        maxLength: 10
        minLength: 1
        pattern: ^(?!\s*$).+
        type: string
      style: form
  schemas:
    filename:
      description: Full name and extension of the ingested eTUFF tag data file
      example: eTUFF-sailfish-117259_2.txt
      title: filename
      type: string
    event200:
      description: Information for a given event
      example:
        event_id: 06335e84-2872-4914-8c5d-3ed07d2a2dj4
        tag_id: 1
        submission_id: 1
        event_category: submission
        event_name: new tag submission
        time_start: 2022-04-01T04:58:21.319061+00:00
        time_end: 2022-04-01T04:59:21.319061+00:00
        duration: 0:01:00
        event_status: finished
        event_notes: Some user defined notes...
      properties:
        event_category:
          description: '...'
          example: '...'
          type: string
        event_id:
          description: UUID associated with a particular event
          example: 06335e84-2872-4914-8c5d-3ed07d2a2f16
          format: uuid
          title: event_id
          type: string
        event_name:
          description: '...'
          example: '...'
          type: string
        event_notes:
          description: Free-form text field where details of the event can be optionally
            entered by the client
          example: "The event represents a data anomaly with file XYZ because of ...,\
            \ this has been fixed in version ABC."
          type: string
        event_status:
          description: Free-form text field where details of the event can be optionally
            entered by the client
          enum:
          - failed
          - finished
          - killed
          - running
          example: failed
          type: string
        time_start:
          description: Local datetime stamp at the time of the event start
          example: 2022-04-01T04:58:21.319061+00:00
          type: string
        time_end:
          description: Local datetime stamp at the time of the event end
          example: 2022-04-01T04:58:21.319061+00:00
          type: string
        duration:
          description: The event duration e.g. different between 'time_start' and
            'time_end'
          example: 0:01:00
          type: string
        submission_id:
          description: Unique numeric ID assigned upon submission of a tag eTUFF data
            file for ingest/importation into Tagbase
          example: 5
          title: submission_id
          type: integer
        tag_id:
          description: Unique numeric tag ID associated with the ingested tag data
            file
          example: 1
          title: tag_id
          type: integer
      title: event200
      type: object
    eventPut200:
      description: Event update response
      example:
        code: "200"
        message: Notes for event '1' successfully updated.
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        message:
          description: A string detailing specifics of the HTTP operation
          example: Notes for event '1' successfully updated.
          type: string
      title: eventPut200
      type: object
    event_id:
      description: UUID associated with a particular event
      example: 06335e84-2872-4914-8c5d-3ed07d2a2f16
      format: uuid
      title: event_id
      type: string
    events200:
      description: Response detailing all available events
      example:
        count: 3
        events:
        - event_id: 06335e84-2872-4914-8c5d-3ed07d2a2f16
          tag_id: 1
          submission_id: 1
        - event_id: 06335e84-2872-4914-8c5d-3ed07d2a2dj4
          tag_id: 1
          submission_id: 1
        - event_id: 06335e84-2872-4914-8c5d-3ed07d2a2fkf
          tag_id: 1
          submission_id: 1
      properties:
        count:
          description: Total count of unique events
          example: 3
          type: integer
        events:
          description: List of event UUID's and associated tag and submission IDs
          items:
            $ref: '#/components/schemas/events200_events_inner'
          type: array
      title: tags200
      type: object
    ingest200:
      description: HTTP 200 success response
      example:
        code: "200"
        elapsed: 0:00:06.506691
        message: Data file eTUFF-sailfish-117259.txt successfully ingested into Tagbase
          DB
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        elapsed:
          description: Elapsed time for the operation
          type: string
        message:
          description: A string detailing specifics of an HTTP operation
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB
          type: string
      title: ingest200
      type: object
    response500:
      description: 500 Internal Server Error
      example:
        code: "200"
        message: Unable to connect to the Tagbase database
        more_info: https://httpwg.org/specs/rfc7231.html#status.500
        trace: 123e4567-e89b-12d3-a456-426614174000
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        message:
          description: A string detailing specifics of the HTTP 500 response
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB
          type: string
        more_info:
          description: Additional details (if available) to diagnose the 500 response
          example: https://httpwg.org/specs/rfc7231.html#status.500
          type: string
        trace:
          description: Trace diagnostic information related to the response
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
      title: response500
      type: object
    submission_id:
      description: Unique numeric ID assigned upon submission of a tag eTUFF data
        file for ingest/importation into Tagbase
      example: 5
      title: submission_id
      type: integer
    tag200:
      description: Information for a given tag
      example:
        tag:
        - date_time: 2022-04-01T04:58:21.319061+00:00
          filename: eTUFF-sailfish-117259_2.txt
          metadata:
            person_owner: John Do
            owner_contect: john@do.net
            manufacturer: telemetry inc.
            model: new_gen
            attachment_method: anchor
          notes: Ingested by admin on 2022-06-01 for Sailfish tagging campaign.
          submission_id: 5
          tag_id: 3
          version: "1"
        - date_time: 2022-06-01T05:39:46.896088+00:00
          filename: eTUFF-sailfish-117259_2.txt
          metadata:
            person_owner: Jane Do
            owner_contect: jane@do.net
            manufacturer: telemetry inc.
            model: newer_gen
            attachment_method: anchor
          notes: Ingested by admin on 2022-06-01 for version 2 of the Sailfish tagging
            campaign.
          submission_id: 6
          tag_id: 3
          version: "2"
      properties:
        tag:
          description: List containing submissions for a given tag
          items:
            $ref: '#/components/schemas/tag200_tag_inner'
          type: array
      title: tag200
      type: object
    tagPut200:
      description: HTTP 200 success response
      example:
        code: "200"
        message: Tag '1' submission '5' successfully updated.
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        message:
          description: A string detailing specifics of an HTTP operation
          example: Tag '1' submission '5' successfully updated.
          type: string
      title: tagPut200
      type: object
    tag_id:
      description: Unique numeric tag ID associated with the ingested tag data file
      example: 1
      title: tag_id
      type: integer
    tags200:
      description: Response detailing all available unique tags and associated filename
      example:
        count: 2
        tags:
        - tag_id: 1
          filename: eTUFF-sailfish-117259_2.txt
        - tag_id: 2
          filename: eTUFF-sailfish-117259.txt
      properties:
        count:
          description: Total count of unique tags
          example: 2
          type: integer
        tags:
          description: List of unique numeric Tag IDs and associated filename
          items:
            $ref: '#/components/schemas/tags200_tags_inner'
          type: array
      title: tags200
      type: object
    events200_events_inner:
      description: UUID and associated tag and submission ID
      example:
        event_id: 06335e84-2872-4914-8c5d-3ed07d2a2dj4
        tag_id: 1
        submission_id: 1
      properties:
        event_id:
          description: UUID associated with a particular event
          example: 06335e84-2872-4914-8c5d-3ed07d2a2f16
          format: uuid
          title: event_id
          type: string
        tag_id:
          description: Unique numeric tag ID associated with the ingested tag data
            file
          example: 1
          title: tag_id
          type: integer
        submission_id:
          description: Unique numeric ID assigned upon submission of a tag eTUFF data
            file for ingest/importation into Tagbase
          example: 5
          title: submission_id
          type: integer
      title: events200_events_inner
      type: object
    tag200_tag_inner:
      properties:
        date_time:
          description: Local datetime stamp at the time of eTUFF tag data file ingestion
          example: 2022-04-01T04:58:21.319061+00:00
          title: date_time
          type: string
        filename:
          description: Full name and extension of the ingested eTUFF tag data file
          example: eTUFF-sailfish-117259_2.txt
          title: filename
          type: string
        metadata:
          additionalProperties:
            type: string
          description: Contains the ingested tag metadata consistent with the eTUFF
            specification
          example:
            person_owner: John Do
            owner_contect: john@do.net
            manufacturer: telemetry inc.
            model: new_gen
            attachment_method: anchor
          title: metadata
          type: object
        notes:
          description: "Free-form text field where details of submitted eTUFF file\
            \ for ingest can be provided e.g. submitter name, etuff data contents\
            \ (tag metadata and measurements + primary position data, or just secondary\
            \ solutionpositional meta/data)"
          example: Ingested by admin on XXXX-XX-XX to back-process campaign XYZ.
          title: notes
          type: string
        submission_id:
          description: Unique numeric ID assigned upon submission of a tag eTUFF data
            file for ingest/importation into Tagbase
          example: 5
          title: submission_id
          type: integer
        tag_id:
          description: Unique numeric tag ID associated with the ingested tag data
            file
          example: 1
          title: tag_id
          type: integer
        version:
          description: Version identifier for the eTUFF tag data file ingested
          example: "1"
          title: version
          type: string
      title: tag200_tag_inner
      type: object
    tags200_tags_inner:
      description: Unique numeric Tag ID associated with the ingested tag eTUFF data
        file
      example:
        tag_id: 1
        filename: eTUFF-sailfish-117259_2.txt
      properties:
        tag_id:
          description: Unique numeric tag ID associated with the ingested tag data
            file
          example: 1
          title: tag_id
          type: integer
        filename:
          description: Full name and extension of the ingested eTUFF tag data file
          example: eTUFF-sailfish-117259_2.txt
          title: filename
          type: string
      title: tags200_tags_inner
      type: object
